# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Add this line to fix Firebase issues
use_modular_headers!

# Enable GPU acceleration for react-native-fast-tflite
# CoreML Delegate provides 3-10x performance improvement on iOS
$EnableCoreMLDelegate = true
$EnableMetalDelegate = true

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'PhysioAssist' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'PhysioAssistTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # react-native-worklets-core imports <ReactCommon/RCTTurboModule.h>, but on the old
    # architecture its podspec doesn't depend on React-NativeModulesApple (which ships
    # that header) or the pods it includes, so the header isn't on its search path.
    installer.pods_project.targets.each do |target|
      next unless target.name == 'react-native-worklets-core'
      target.build_configurations.each do |build_config|
        paths = build_config.build_settings['HEADER_SEARCH_PATHS'] || ['$(inherited)']
        paths = paths.split(' ') if paths.is_a?(String)
        build_config.build_settings['HEADER_SEARCH_PATHS'] = paths + %w[
          React-NativeModulesApple ReactCommon React-callinvoker React-jsi
        ].map { |pod| "\"$(PODS_ROOT)/Headers/Public/#{pod}\"" }
      end
    end
  end
end
